from pptx import Presentation
from pptx.util import Inches, Pt
import os

def create_project_presentation():
    prs = Presentation()
    
    # 1. Title Slide
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    title.text = "Multi-Project Status Report"
    subtitle.text = "Singularity, Archimedes, & Digital Twin\nGenerated by Antigravity Agent"

    # 2. Singularity Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Singularity: Trading Intelligence"
    content = slide.placeholders[1].text_frame
    content.text = "• Goal: 10,000 TWD Challenge"
    content.add_paragraph().text = "• V3 Adaptive Logic with RSI & Bollinger Bands"
    content.add_paragraph().text = "• Real-time Sentiment Filter (Fear & Greed Index)"
    content.add_paragraph().text = "• Daily Autonomic Self-Optimization active"

    # 3. Archimedes' Hand Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Archimedes' Hand: Robotics"
    content = slide.placeholders[1].text_frame
    content.text = "• Whole-Body Coordination v3.1"
    content.add_paragraph().text = "• Multi-Terrain Adaptation (Mud, Sand, Water)"
    content.add_paragraph().text = "• AME-2 Based Directional Terrain Scanning"
    content.add_paragraph().text = "• 5.0M Step Pre-trained Arm Model completed"

    # 4. Digital Twin Slide
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "NM-REF-100 Digital Twin"
    content = slide.placeholders[1].text_frame
    content.text = "• PINNs Physics-Informed Neural Network"
    content.add_paragraph().text = "• Fick's Second Law embedded in Loss Function"
    content.add_paragraph().text = "• 10,000 Hour Reliability Prediction"
    
    # Add Heatmap if exists
    img_path = "/home/aa598/.openclaw/workspace/digital-twin/nm-ref-100/assets/pinn_soh_prediction_heatmap.png"
    if os.path.exists(img_path):
        prs.slides.add_slide(prs.slide_layouts[5]).shapes.add_picture(img_path, Inches(1), Inches(1.5), width=Inches(8))

    output_file = "Project_Master_Status.pptx"
    prs.save(output_file)
    return output_file

if __name__ == "__main__":
    path = create_project_presentation()
    print(f"✅ Presentation created: {path}")
